# Generated by Django 5.1.7 on 2025-03-17 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.IntegerField(choices=[(0, 'Fonte'), (1, 'Placa-mãe'), (2, 'Processador'), (3, 'Memória RAM'), (4, 'Placa De Vídeo'), (5, 'Desconhecido')], default=5)),
                ('nome', models.CharField()),
                ('marca', models.CharField()),
                ('modelo', models.CharField()),
                ('especificacoes', models.JSONField()),
                ('imagem', models.CharField()),
                ('data_adicionado', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('data_criacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Precos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_produto', models.URLField()),
                ('preco', models.FloatField()),
                ('data_coleta', models.DateField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.lojas')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.produtos')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.users')),
            ],
        ),
        migrations.CreateModel(
            name='Builds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.ForeignKey(limit_choices_to={'categoria': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='build_cpu', to='db.produtos')),
                ('gpu', models.ForeignKey(limit_choices_to={'categoria': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_gpu', to='db.produtos')),
                ('mobo', models.ForeignKey(limit_choices_to={'categoria': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='build_mobo', to='db.produtos')),
                ('psu', models.ForeignKey(limit_choices_to={'categoria': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='build_psu', to='db.produtos')),
                ('ram', models.ForeignKey(limit_choices_to={'categoria': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='build_ram', to='db.produtos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.users')),
            ],
        ),
    ]
