# Generated by Django 5.1.7 on 2025-03-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="senha",
            field=models.TextField(),
        ),
    ]
