# Generated by Django 5.1.7 on 2025-04-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_users_senha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritos',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='lojas',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='precos',
            old_name='data_coleta',
            new_name='colected_date',
        ),
        migrations.RenameField(
            model_name='precos',
            old_name='preco',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='precos',
            old_name='produto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='precos',
            old_name='url_produto',
            new_name='url_product',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='data_adicionado',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='especificacoes',
            new_name='especifications',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='imagem',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='modelo',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='data_criacao',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='senha',
            new_name='password',
        ),
    ]
