# Generated by Django 5.1.7 on 2025-05-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_users_favoritos_user_rename_nome_lojas_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='especifications',
            new_name='specifications',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='model',
        ),
    ]
